apiVersion: 1

datasources:
  - name: MBlog PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: blog_db
    user: postgres
    secureJsonData:
      password: '4341289'
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
    isDefault: true
