version: '3'
services:
  frontend:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ../frontend/docs/.vitepress/dist:/usr/share/nginx/html
      - ../frontend/nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  backend:
    build: ../backend
    ports: ["3000:3000"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4341289
      POSTGRES_DB: blog_db    
    ports:  # 新增此行
      - "5432:5432"  # 将容器5432映射到宿主机5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
